### ISSUE TITLE
Tab completion on remote console

### ISSUE THREAD

**Issue by ConnorRigby** [nerves-hub/nerves_hub_link#4]
IO servers can have their own tab expansion handlers:

```elixir
fun = fn(str) ->
  {:yes, 'aa', ['aa1', 'aab', 'aac']}
end
:io.setopts(:expand_fun, fun)
```

We can use this to tunnel tab completion for the remote console

**Comment by ConnorRigby** [comment]
and [here](https://github.com/elixir-lang/elixir/blob/06c2ab093d5470b10474f7a552a37c3184c24afd/lib/iex/lib/iex.ex#L814-L829) is the Elixir implementation. It should be easy to take this exact code for the remote console, then it's just a matter of capturing the `tab` event from javascript

**Comment by jjcarstens** [comment]
Going this route will mean we'll need to get more specific in how we handle IO in the channel because we currently [ignore all `setopts` functions](https://github.com/nerves-hub/nerves_hub_link/blob/master/lib/nerves_hub_link/console_channel.ex#L151-L155).

But, I'm pretty sure we can set this _before_ reassigning group leader. In fact, I'm also fairly sure this is already set for us by using `IEx.Server.run`.

Also, I believe another issue to overcome here is that using `IEx.Server.run` starts a loop with [`IO.gets`](https://github.com/elixir-lang/elixir/blob/master/lib/iex/lib/iex/server.ex#L327), which in turn calls to `:io.get_line` - The `get_line` is always expecting a full line at a time and evaluates the input as a whole so we can't really get tab events into it to run the evaluator. I don't have a solution, but I'm _really_ confident that is part of the problem

**Comment by jjcarstens** [comment]
Also adding a note to consider IEx history (responding to up/down keys from web) here as well since that is likely very related. If it ends up being a different path, we can split out the issue

**Comment by fhunleth** [comment]
Tab completion works on the new console!!
